spin_manifest_version = 2

[application]
authors = ["Nicole Venner <nvenner@protonmail.ch>"]
description = ""
name = "seance-backend-spin"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "seance-backend-spin"

[component.seance-backend-spin]
source = "dist/seance-backend-spin.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = [
    # "tcp://127.0.0.1:*", # Uncomment this line to while using the StarlingMonkey Debugger
]
[component.seance-backend-spin.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]